-- Create sub_vendor_checklists table
CREATE TABLE IF NOT EXISTS public.sub_vendor_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT, -- Using BIGINT for IDs
    vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE SET NULL,
    
    -- Project details
    project_name TEXT,
    location TEXT,
    vendor_company_name TEXT,
    vendor_name TEXT,
    address TEXT,
    phone_no TEXT,
    aadhaar_no TEXT,
    pan_no TEXT,
    gst_no TEXT,
    billing_address TEXT,
    
    -- Bank details
    bank_account_name TEXT,
    bank_account_number TEXT,
    bank_ifsc_code TEXT,
    bank_branch TEXT,
    bank_name TEXT,
    
    -- Budget details
    material_budget NUMERIC DEFAULT 0,
    labour_budget NUMERIC DEFAULT 0,
    total_budget NUMERIC DEFAULT 0,
    final_material_amount NUMERIC DEFAULT 0,
    final_labour_amount NUMERIC DEFAULT 0,
    total_value NUMERIC DEFAULT 0,
    
    -- Purchase details (JSONB for flexibility)
    -- Format: { "Material Purchase": { "vendor": true, "iipl": false }, ... }
    purchase_details JSONB DEFAULT '{}'::jsonb,
    
    -- Payment terms (JSONB for flexibility)
    -- Format: { "advance_pct": 0, "ra_bill_limit": 85, "housekeeping_deduction": "YES", "retention": "YES" }
    payment_terms JSONB DEFAULT '{}'::jsonb,
    
    -- Terms and conditions
    terms_and_conditions TEXT[] DEFAULT ARRAY[
        'Work to be executed as per approved drawings',
        'No extra work without written approval',
        'Quality to be approved by site engineer',
        'Running Bill Should be Certified by site engineer',
        'All debits will be recovered from vendor bills',
        'Vendor responsible for labour safety',
        'If Any deduction recommended by Site In-charge',
        'Sub Vendor is not permitted to take any work directly from the project client or any other vendor work in the same project'
    ],
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by TEXT
);

-- Enable RLS
ALTER TABLE public.sub_vendor_checklists ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users for now
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sub_vendor_checklists' AND policyname = 'Allow authenticated users to manage sub_vendor_checklists') THEN
        CREATE POLICY "Allow authenticated users to manage sub_vendor_checklists" ON public.sub_vendor_checklists FOR ALL USING (true);
    END IF;
END
$$;
